-- ==========================
-- fichier 	: ddl_portPlaisance_DR.sql
-- base 	: port plaisance
-- auteur   : Tania OLIVIA
-- date 	: 28/01/2020
-- role 	: créer toutes les dépendances de références
-- projet 	: port plaisance
-- resultat dans : 
-- ==========================

ALTER TABLE BATEAU_RESIDENT
    ADD CONSTRAINT  FK_BRPROP 
        FOREIGN KEY (ID_PROP)
        REFERENCES  PROPRIETAIRE (ID_PROP);

ALTER TABLE BATEAU_RESIDENT
    ADD CONSTRAINT  FK_BRPOR
        FOREIGN KEY  (CODPORT)
        REFERENCES PORT (CODPORT);

ALTER TABLE BATEAU_RESIDENT
    ADD CONSTRAINT  FK_BRMOD
        FOREIGN KEY  (ID_MOD)
        REFERENCES MODELE (ID_MOD);

ALTER TABLE BATEAU_RESIDENT
    ADD CONSTRAINT  FK_BRBP
        FOREIGN KEY  (EMPL_AFF)
        REFERENCES EMPLACEMENT (ID_EMPL);

ALTER TABLE BATEAU_PASSAGE
    ADD CONSTRAINT  FK_BPPOR
        FOREIGN KEY  (CODPORT)
        REFERENCES PORT (CODPORT);

ALTER TABLE BATEAU_PASSAGE
    ADD CONSTRAINT  FK_BPMOD
        FOREIGN KEY  (ID_MOD)
        REFERENCES MODELE (ID_MOD);

ALTER TABLE BATEAU_PASSAGE
    ADD CONSTRAINT  FK_BPBR
        FOREIGN KEY  (EMPL_AFF)
        REFERENCES EMPLACEMENT (ID_EMPL);

ALTER TABLE EMPLACEMENT_LIBRE
    ADD CONSTRAINT  FK_EMPLACEMENT_LIBRE_EMPL
        FOREIGN KEY  (ID_EMPL)
        REFERENCES EMPLACEMENT (ID_EMPL);

ALTER TABLE EMPLACEMENT_LIBRE
    ADD CONSTRAINT  FK_EMPLACEMENT_LIBRE_TYP
        FOREIGN KEY  (TYPE_EMPL)
        REFERENCES TYPE_EMPLACEMENT (TYPE_EMPL);

ALTER TABLE EMPLACEMENT
    ADD CONSTRAINT  FK_EMPL_TYP
        FOREIGN KEY  (TYPE_EMPL)
        REFERENCES TYPE_EMPLACEMENT (TYPE_EMPL);

ALTER TABLE SORTIE
    ADD CONSTRAINT  FK_SORTBRCOD
        FOREIGN KEY  (NOMBAT, CODPORT)
        REFERENCES BATEAU_RESIDENT (NOMBAT, CODPORT);
