-- ==========================
-- fichier 	: ddl_portPlaisance_DROP.sql
-- base 	: port plaisance
-- auteur   : Tania OLIVIA
-- date 	: 28/01/2020
-- role 	: supprimer l'ensemble des tables
-- projet 	: port plaisance
-- resultat dans :
-- ==========================

DROP TABLE SORTIE CASCADE CONSTRAINTS;
DROP TABLE BATEAU_RESIDENT CASCADE CONSTRAINTS;
DROP TABLE BATEAU_PASSAGE CASCADE CONSTRAINTS;
DROP TABLE EMPLACEMENT_LIBRE CASCADE CONSTRAINTS;
DROP TABLE PROPRIETAIRE CASCADE CONSTRAINTS;
DROP TABLE PORT CASCADE CONSTRAINTS;
DROP TABLE MODELE CASCADE CONSTRAINTS;
DROP TABLE EMPLACEMENT CASCADE CONSTRAINTS;
DROP TABLE TYPE_EMPLACEMENT CASCADE CONSTRAINTS;
