-- ============================================================================
-- Fichier          : description_base_billetterie.sql
-- Auteur           : Brouillé Théo
-- Date             : Janvier 2019
-- Base				: Billetterie
-- Role             : Décrit le schéma de la base Billetterie et ses contraintes
-- Fichier resultat : description_base_billetterie.out
-- ============================================================================


SPOOL description_base_billetterie.out

COLUMN CCOLUMN FORMAT A10
COLUMN RCOLUMN FORMAT A10
COLUMN RTABLE FORMAT A10
COLUMN COND FORMAT A28
COLUMN CNAME FORMAT A15

-----------------------------------------------------------------------

PROMPT Schéma de la relation Client :
DESC Client;

PROMPT Clés primaires et uniques de Client
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Client')
AND C.CONSTRAINT_TYPE IN ('P','U');

PROMPT Clés étrangères de Client
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, T.TABLE_NAME AS RTABLE,
T.COLUMN_NAME AS RCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U, USER_CONS_COLUMNS T
WhERE C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Client')
AND C.CONSTRAINT_TYPE = 'R'
AND U.CONSTRAINT_NAME = T.CONSTRAINT_NAME
AND U.CONSTRAINT_NAME = C.CONSTRAINT_NAME;

PROMPT Constraintes CHECK de Client
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, SEARCH_CONDITION AS COND
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Client')
AND C.CONSTRAINT_TYPE = 'C';

-----------------------------------------------------------------------

PROMPT Schéma de la relation Billet :
DESC Billet;

PROMPT Clés primaires et uniques de Billet
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Billet')
AND C.CONSTRAINT_TYPE IN ('P','U');

PROMPT Clés étrangères de Billet
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, T.TABLE_NAME AS RTABLE,
T.COLUMN_NAME AS RCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U, USER_CONS_COLUMNS T
WhERE C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Billet')
AND C.CONSTRAINT_TYPE = 'R'
AND U.CONSTRAINT_NAME = T.CONSTRAINT_NAME
AND U.CONSTRAINT_NAME = C.CONSTRAINT_NAME;

PROMPT Constraintes CHECK de Billet
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, SEARCH_CONDITION AS COND
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Billet')
AND C.CONSTRAINT_TYPE = 'C';

-----------------------------------------------------------------------

PROMPT Schéma de la relation Evenement :
DESC Evenement;

PROMPT Clés primaires et uniques de Evenement
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Evenement')
AND C.CONSTRAINT_TYPE IN ('P','U');

PROMPT Clés étrangères de Evenement
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, T.TABLE_NAME AS RTABLE,
T.COLUMN_NAME AS RCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U, USER_CONS_COLUMNS T
WhERE C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Evenement')
AND C.CONSTRAINT_TYPE = 'R'
AND U.CONSTRAINT_NAME = T.CONSTRAINT_NAME
AND U.CONSTRAINT_NAME = C.CONSTRAINT_NAME;

PROMPT Constraintes CHECK de Evenement
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, SEARCH_CONDITION AS COND
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Evenement')
AND C.CONSTRAINT_TYPE = 'C';

-----------------------------------------------------------------------

PROMPT Schéma de la relation Salle :
DESC Salle;

PROMPT Clés primaires et uniques de Salle
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Salle')
AND C.CONSTRAINT_TYPE IN ('P','U');

PROMPT Clés étrangères de Salle
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, T.TABLE_NAME AS RTABLE,
T.COLUMN_NAME AS RCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U, USER_CONS_COLUMNS T
WhERE C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Salle')
AND C.CONSTRAINT_TYPE = 'R'
AND U.CONSTRAINT_NAME = T.CONSTRAINT_NAME
AND U.CONSTRAINT_NAME = C.CONSTRAINT_NAME;

PROMPT Constraintes CHECK de Salle
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, SEARCH_CONDITION AS COND
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Salle')
AND C.CONSTRAINT_TYPE = 'C';

-----------------------------------------------------------------------

PROMPT Schéma de la relation Tarif :
DESC Tarif;

PROMPT Clés primaires et uniques de Tarif
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Tarif')
AND C.CONSTRAINT_TYPE IN ('P','U');

PROMPT Clés étrangères de Tarif
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, T.TABLE_NAME AS RTABLE,
T.COLUMN_NAME AS RCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U, USER_CONS_COLUMNS T
WhERE C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Tarif')
AND C.CONSTRAINT_TYPE = 'R'
AND U.CONSTRAINT_NAME = T.CONSTRAINT_NAME
AND U.CONSTRAINT_NAME = C.CONSTRAINT_NAME;

PROMPT Constraintes CHECK de Tarif
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, SEARCH_CONDITION AS COND
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('Tarif')
AND C.CONSTRAINT_TYPE = 'C';

-----------------------------------------------------------------------

PROMPT Schéma de la relation SiteResa :
DESC SiteResa;

PROMPT Clés primaires et uniques de SiteResa
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('SiteResa')
AND C.CONSTRAINT_TYPE IN ('P','U');

PROMPT Clés étrangères de SiteResa
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, T.TABLE_NAME AS RTABLE,
T.COLUMN_NAME AS RCOLUMN
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U, USER_CONS_COLUMNS T
WhERE C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('SiteResa')
AND C.CONSTRAINT_TYPE = 'R'
AND U.CONSTRAINT_NAME = T.CONSTRAINT_NAME
AND U.CONSTRAINT_NAME = C.CONSTRAINT_NAME;

PROMPT Constraintes CHECK de SiteResa
SELECT C.CONSTRAINT_TYPE AS CTYPE, C.CONSTRAINT_NAME AS CNAME, U.COLUMN_NAME AS CCOLUMN, SEARCH_CONDITION AS COND
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS U
WHERE C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
AND C.TABLE_NAME = U.TABLE_NAME
AND upper(C.TABLE_NAME) = upper('SiteResa')
AND C.CONSTRAINT_TYPE = 'C';

SPOOL OFF
